apiVersion: v1
kind: Secret
metadata:
  name: market-monitor-secrets
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:KGr/IYyr8Bwhr9nazJ4rAZ+Xt0NubhCzaWRhNQs+oSrdCsQ+F0b4pko8DpmD20ZQzDoUQhaO3ZXv6imTN1LFFw==,iv:cVsvQdRm/YIes2DL1+ymA0dPpEfHuoi7OxkiRfu04p4=,tag:q/qwXUFxrAh3oznT7Xipcw==,type:str]
  REFRESH_TOKEN_SECRET: ENC[AES256_GCM,data:05sgEJ/6a1kjw5BfTssIzxCEc7cZZ8JN6U9nZ1iU1bLjgJmS6a6UtF1AY1XmHqJK4daFX5fZvE4ya1jT/iwqww==,iv:VHsK/wu36xRbY28r3q4mhIcqVLtYz0JFS4jmvHwlAA4=,tag:VkdzRPBz5CfEvS3fg8PdYA==,type:str]
  NUXT_SESSION_PASSWORD: ENC[AES256_GCM,data:yOX7hJPG3rRWJzcLQGOJgjPKfhdv9YEFzwZ2GhwmIHIA/dxdwPCze+Ss2g0NkG2JshYI/T3U6ArYanxEezMHQw==,iv:wC9b8C1XDKSsqmPff6xlgietnSeYiQa9rhqQs48oya4=,tag:1vLxY2ILl8UejgKtyWVDDA==,type:str]
sops:
  age:
    - recipient: age10ppc643t645d2ph0czpz64zq9ezj0j9xu0c0mjytm6a34fzulqhqa8pp2k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUFdvWjY0R0QzT2VCUW1R
        U3Q0cGxkbXVFbWdKcndTTTBzWmc2OGlEa0ZBCjMzbEhaTFhXbDYxTCt2VjhzVmpw
        Vm9LMjZkUVJLdzI1MHNJc2lUajY5Vm8KLS0tIEZXcEoyMDRDQUQ2T2Z0dmh0MFc4
        N0kvbWNWdS9YY2tITjBCRnN1dWgvQ2cK3lDp6zM1Ks/kSUgiI8JkPcjEGHDTIb8u
        kWPgx5NXEncKST0Tg0pG4W9Ox0KEPYIKdJHiVjwvaLuH4yhLd2/IDA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T12:15:06Z"
  mac: ENC[AES256_GCM,data:WaZrFHv9I7BfAY6Lvp+6OFBsgV4rsQqvi8UJnAq8zgPqfwbXtnN3maf5ngNWYVqmpFA5cc8UIvB3mxBrz9htwYSy2uYISKVD0zEhpXnZQAoYh7SDVDHoI2k11Tcffa8a1dosk0onqmJSqvX6Pr/AR2i8U9o7rV6faLzTM5yuRr0=,iv:BpFp1yIHyJxHOb44FdlHcNcsbyJOiGrZsbZ2XmL4oFU=,tag:TRfvyVbpuTX7/lh5JmfP1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
