apiVersion: v1
kind: Service
metadata:
  name: market-monitor
  labels:
    app: market-monitor
spec:
  type: ClusterIP
  ports:
    - port: 3847
      targetPort: 3847
      protocol: TCP
      name: ui
    - port: 5847
      targetPort: 5847
      protocol: TCP
      name: api
  selector:
    app: market-monitor
